FROM  grafana/grafana:6.5.0
RUN  grafana-cli plugins install alexanderzobnin-zabbix-app && \ 
     grafana-cli plugins install grafana-piechart-panel && \
     grafana-cli plugins install raintank-worldping-app && \
     grafana-cli plugins install  percona-percona-app
